#!/bin/bash

EVENTS="MODIFY"
WATCH_FILES="server.py ticker.py templates/index.html static/*"

CONTINUE=1

function get_pid()
{
   ps aux| grep "python3 ./server.py" | grep -v "grep" | tr -s ' ' | cut -d' ' -f2
}

function kill_servers()
{
  while :
  do
      RUNNING=$(get_pid);
      if [ -z "$RUNNING" ];
      then
        break
      else
        echo "Killing old process " $RUNNING
        kill -9 $RUNNING
      fi
  done
}

trap ctrl_c INT
function ctrl_c() {
  CONTINUE=0
  echo "Exiting..."
  kill_servers
}

kill_servers
while [ $CONTINUE -gt 0 ];
do
    ./server.py&
    RUNNING=$(get_pid)
    echo "Starting instance $RUNNING"
    inotifywait -q -e $EVENTS $WATCH_FILES 2>&1 >/dev/null
    kill_servers
done
